services:
  db:
    image: postgres:16-alpine
    container_name: school-db
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "54325:5432"  # Maps Host 54325 to Container 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: