spring.application.name=school


# 1. Connection (Port 5432 matches your 'docker ps' output)
spring.datasource.url=jdbc:postgresql://localhost:54325/school
spring.datasource.username=postgres
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate (Switch to 'validate' so it checks but doesn't change the DB)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Flyway Migration
spring.flyway.enabled=true
# Optional: If you want Flyway to clean the DB (use with caution!)
spring.flyway.clean-disabled=false